export const botonesMetodos = {
    razonesLiquidez: ["Razón Circulante", "Razón Rápida"],
    razonesEndeudamiento: ["Deuda Total", "Deuda Largo Plazo"],
    razonesRentabilidad: ["Rentabilidad sobre el Capital", "Rentabilidad sobre el Activo"],
    razonesActividad: ["Rotación de Activos", "Días de Cobranza"],
    ppp: "Periodo Promedio de Pago",
    ppc: "Periodo Promedio de Cobro",
    calcularROE: "ROE (Rendimiento sobre el Patrimonio)",
    calcularPG: "P/G (Razón Precio/Ganancias)",
    calcularROA: "ROA (Rendimiento sobre los Activos Totales)",
    calcularWACC: "WACC (Costo Promedio Ponderado de Capital)",
    calcularCostoDeudaAntesImpuestos: "Costo de la Deuda antes de Impuestos",
    analisisVertical: "Análisis Vertical",
    analisisHorizontal: "Análisis Horizontal",
    calcularPuntoEquilibrio: "Punto de Equilibrio",
    calcularRazonCargosInteresFijo: "Razón de Cargos de Interés Fijo",
    calcularRazonDeudaCapitalPatrimonial: "Razón Deuda/Capital Patrimonial",
    calcularMargenUtilidadBruta: "Margen de Utilidad Bruta",
    calcularRotacionActivosTotales: "Rotación de Activos Totales",
    calcularRazonCoberturaPagosFijos: "Razón de Cobertura de Pagos Fijos",
    calcularMargenUtilidadOperativa: "Margen de Utilidad Operativa",
    calcularMargenUtilidadNeta: "Margen de Utilidad Neta",
    calcularGananciasDisponibles: "Ganancias Disponibles para Accionistas",
    calcularValorEnLibrosPorAccion: "Valor en Libros por Acción",
    ROA: "ROA (Rendimiento sobre los Activos)",
    ROE: "ROE (Rendimiento sobre el Patrimonio)"
};
